### ISSUE TITLE
Design-refresh: page-by-page review/sweep

### ISSUE THREAD

**Issue by stevejalim** [mdn/developer-portal#1233]
Seeking inconsistencies with design and/or between browsers, plus glitches

- [x] HTML Validation re-checks
  - [x] Particularly when SVGs are in play and may need still cruft removing from them

- [x] Cross-browser re-testing
  - [x] Desktop layout
  - [x] Mobile layout
  - [ ] Medium-breakpoint layout

## Snags that need fixing
- [x] People page: topic cards
  - [x] (P1) short title (eg "CSS") is too short to force reflow, needs to be done _with_ CSS --> `width: 100%;` ?
  - [x] (P1) glitched layout in mobile mode -> `body.person .topic-links .mzp-c-card-content` needs to be block, not inline-block (hopefully easy fix)

- [x] (P1) IE11 newsletter signup fails: 'fetch' is undefined.

- [x] (P2) Mozilla Developer logo: Shift 1px or 2px higher compared to menu text?

- [x] (P2) Events list: optional rich-text area/CTA button could do with better positioning

- [x] (P1) Filter list when there's a "Cancel X" link present because fiters are active, needs better spacing

- [x] (P1) IE11: video lightbox not working -> `Object doesn't support property or method "assign"`. Polyfill time.

- [x] (P2) Mobile view of homepage: CTA bar could do with a bit more space above button

- [x] (P2) FILTER LIST Mobile Safari shows rounded-corner button

- [x] Bad hover state on topic cards (see [here](https://app.zenhub.com/workspaces/mdn-developer-portal-5d41d915e27a7b3dba9111ad/issues/mdn/developer-portal/1233#issuecomment-620579790))

## Needs discussion + own tickets

- [x] (P2) Currently the Posts page does not display the header image - do we want to show it? If so, how? --> TICKETED AS #1421

- [ ] (P2) middle-size BREAKPOINT with three/four reflows poorly, compared to mozilla.org -- see how they do it, could be an easy fix? TICKETED AS #1422

## Snags from code review (need own tickets)
- [x] drop use of `section` unless it really really makes sense
- [x] reinstate `role=main` where appropriate
- [ ] add `display: block` to button stacks in mobile + change to UL [see here](https://github.com/mdn/developer-portal/pull/1313#pullrequestreview-383680148)  -> can live without this
- [x] address reflow of header SVG icon on mobile [see here](https://github.com/mdn/developer-portal/pull/1313#issuecomment-605885294)

## nice-to-dos from code review or cross-browser testing (need own tickets)
 - [ ] add support for lazy-loading images that are offscreen at page load -> TICKETED AS #1423
 - [ ] IE11 in narrow-viewport view: filter toggle controls are duplicated [see here](https://github.com/mdn/developer-portal/pull/1327#issuecomment-606360223)  -> WONTFIX. It works, but is a UI glitch.
- [ ] check fonts
- [ ] P5 / NICE TO DO: Filter-list, post filtering, should go to the named anchor, like with pagination, if possible --> TICKETED AS #1425
- [ ] (P2) Server error page - let's use the pretty one in k8s/with the CDN -> TICKETED AS #1424 - no need for this to be part of the redesign

**Comment by valgrimm** [comment]
[ ] check fonts

Note from Steve, check fonts 
"We may need a font review in the sweep - i notice that the rich-text content uses the serif font not the sans-serif face"

**Comment by stevejalim** [comment]
Noticed this dodgy hover:

![Screenshot 2020-04-28 at 13.37.57.png](https://images.zenhubusercontent.com/5d7b94dd167772000187fd33/db6d52e3-28ee-4223-b3ee-c3c7712abbdc)
