### ISSUE TITLE
As a site visitor I want to search for post titles and descriptions  . . . 

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1450]
Full story: As a site visitor I want to search for post titles and descriptions within topic categories so that I can find specific posts without paging through a long list

AC
- [ ] A search bar should be present on the Posts page adjacent to the filters
- [ ] Visitor should be able to search the Title and Description fields for Posts, Videos, External Posts, and External videos within topic categorie(s) after applying filters
- [ ] Visitor should be able to search through Title and Description fields for Posts, Videos, External Posts, and External videos without applying filters
~- [ ] Visitor should be able to view results on default Wagtail search results page~ Replaced by @stevejalim with the following line
- [ ] After searching, the Visitor should see all relevant posts in the standard posts list on the Posts page, filtered by any selected filters and scoped by any search terms provided

**Comment by stevejalim** [comment]
@valgrimm Just wanted to check in with you before breaking this down into child tickets: is the idea here that it's a _different_ kind of search from the overall site search (ie, the results are only ever for Posts), or just that this is a different entry point into the overall site search?

**Comment by stevejalim** [comment]
I get this now - it's basically adding in text search as an addition to the filters on the posts page to help find relevant Posts :thumbsup:

Creating sub-tickets now

**Comment by stevejalim** [comment]
@valgrimm Have slightly tweaked the overall AC so that this Epic is about using search to refine the results shown in the posts list, rather than (my previous suggestion) of taking users to the main search results page - I think it is a better solution and hope you agree
