### ISSUE TITLE
Report: Event, External Post, and Person with Meta tags

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#1563]
AC
- [ ] A plaintext, CSV, or similar listing events by the contents of their name field, with their meta tag(s)
- [ ] A plaintext, CSV, or similar listing external posts by the contents of their title field, with their and meta tag(s)
- [ ] A plaintext, CSV, or similar listing people by name, with their meta tag(s)
(Stretch: A way to generate these reports via django-admin, or directions for generating them myself for the future. However, if report generation functionality requires more than a day of work, drop it. )

**Comment by stevejalim** [comment]
Could this follow shortly after hard launch?

Also, to ensure I'm on the same page: "meta tags" in this context means the Topics associated with them, yep?

**Comment by valgrimm** [comment]
yes, I descoped it from hard launch
