### ISSUE TITLE
Incorrect logo in meta property image

### ISSUE THREAD

**Issue by slightlyoffbeat** [mdn/developer-portal#518]
I noticed that the social sharing image uses a transparent Mozilla logo with a see-through background. 

It should use a solid logo. Feel free to check out https://mozilla.design/mozilla/logo-usage/ for more details.

AC:
- [ ] Default social media image for start page uses developer logo
- [ ] Default image for videos uses developer logo
- [ ] Default image for article uses developer logo
- [ ] Default image for events uses developer logo

**Comment by stevejalim** [comment]
I caught up with @slightlyoffbeat on Slack, who clarified that, ultimately, we're talking about the default placeholder image (which comes up in Slack, for instance, when you share the link to the developer portal).

That placeholder image is:
![example.jpg](https://images.zenhubusercontent.com/5d7b94dd167772000187fd33/9108f7d3-b066-4208-9282-2d7515f547cd)

and the issue is that the white-background Mozilla logo should only be used as a block colour, not with any transparency.

Because I joined the project late on, I'm not sure where these placeholder images came from, but am assuming they came out of some signed-off designs.

@atopal With that extra context in mind, we could:

1) Leave things as they are for alpha, then get new designs made up ASAP
2) Stick with the current designs but re-make them using the block background (assuming we have access to the source images used)
3) Something else - am open to suggestions!

**Comment by atopal** [comment]
Let's switch to the Mozilla Developer logo

**Comment by atopal** [comment]
We should switch all usage of the Mozilla logo over to the developer logo. Let's use the backgrounds if we can, but not a requirement

**Comment by stevejalim** [comment]
@atopal Could you clarify what you mean by the "developer logo"? Is it the purely font-based branding seen at mozilla.org/developer ? 

![Screenshot_20191125-095630](https://user-images.githubusercontent.com/101457/69530660-537ef280-0f6a-11ea-970f-1c6a2aaf32a9.png)

Also, do we want to also update the use of the Mozilla logo top-left the desktop site (the one which links to `/`)? Am assuming yes.

**Comment by atopal** [comment]
Logo + text

**Comment by stevejalim** [comment]
Adding unadorned background images here (thanks @dcgauld!!) because they were not easily findable

![PlaceholderArticle01NoLogo.jpg](https://images.zenhubusercontent.com/5d7b94dd167772000187fd33/81b42704-e43e-48e2-afdc-f1698164c8c9)

![PlaceholderArticle02NoLogo.jpg](https://images.zenhubusercontent.com/5d7b94dd167772000187fd33/6713ee4d-acc8-4d36-9ad1-b8ba03b6b583)

![PlaceholderArticle03NoLogo.jpg](https://images.zenhubusercontent.com/5d7b94dd167772000187fd33/6a63c01d-dbfd-4bdb-a4ca-5115d73f6baa)
