### ISSUE TITLE
SEO: Document does not have a meta description

### ISSUE THREAD

**Issue by valgrimm** [mdn/developer-portal#698]
These pages need meta descriptions:
    * Communities
    * Events
    * Home
    * Topics 

AC:
- [x] Communities have meta descriptions
- [x] Events have meta descriptions
- [x] Home have meta descriptions
- [x] Topics have meta descriptions
- [x] Lighthouse report doesn't complain about missing SEO descriptions

**Comment by valgrimm** [comment]
I've added SEO descriptions, what remains is to check Lighthouse.

**Comment by stevejalim** [comment]
Lighthouse (via Speedcurve) is happy. Closing. Thanks, Val!
