### ISSUE TITLE
Complete Setup of Staging Infrastructure

### ISSUE THREAD

**Issue by tobinmori** [mdn/developer-portal#99]
### Description
For clarity sake, we should think of Devportal as having 3 logical instances (or entry points):
1) devportal CMS (admin where content is entered by content team)
2) devportal dynamic site (dynamically rendered content from what's been entered in the CMS - probably a good place to check that what you've entered looks good, or that a new feature works)
3) devportal published site (statically published pages which will be the public-facing website)

Given the above, the status of staging is this:
#1 lives here https://developer-portal-stage.mdn.mozit.cloud/admin/
#2 lives here: https://developer-portal-stage.mdn.mozit.cloud/

**What needs to be done:**
#3 has not been fully setup, we are publishing the pages to s3, but we need to complete setup on this (CDN/HTTPS cert/DNS) now that we're going with the separate domain option. (it formerly was at /portal on MDN, but has since been taken down).

How about naming the published site:
**https://developer-portal-stage-static.mdn.mozit.cloud**

### Tasks
- [ ] Select a domain name for the published site (perhaps the suggestion above)
- [ ] Create CloudFront CDN with separate behaviors for `/static/*`, `/media/*`, and the default, with all behaviors using the stage S3 bucket for their origin. The `/static/*` and `/media/*` behaviors can have large TTL's while the default cache behavior should have a TTL of about an hour or so.
- [ ] Create CNAME DNS entry for selected domain that points to the CDN
- [ ] Create SSL cert for that domain (this is for the CDN)
- [ ] Test by building and publishing from https://developer-portal-stage.mdn.mozit.cloud/
- [ ] Create the associated Terraform code for repeatability

**Comment by stevejalim** [comment]
Just noticed that the staging site times out when accessed over `http://`, with no auto-redirect to `https://` -- can this be handled at the ALB/ELB level, I wonder

**Comment by limed** [comment]
> Just noticed that the staging site times out when accessed over `http://`, with no auto-redirect to `https://` -- can this be handled at the ALB/ELB level, I wonder

You can with an ALB I believe, however you can't with an ELB which is what we are using. Which was why I was hoping to do the redirect within django itself

**Comment by stevejalim** [comment]
@limed I don't know how current the description of this issue is, but how far away are we from "Staging is up"? Feels pretty close?
